# Prometheus Alert Rules for HPA Platform
groups:
  - name: hpa_platform_alerts
    interval: 30s
    rules:
      # Service availability alerts
      - alert: BackendDown
        expr: up{job="backend"} == 0
        for: 2m
        labels:
          severity: critical
          service: backend
        annotations:
          summary: "Backend API is down"
          description: "Backend API has been down for more than 2 minutes"

      - alert: AgentDisconnected
        expr: up{job="agent"} == 0
        for: 5m
        labels:
          severity: warning
          service: agent
        annotations:
          summary: "Agent is disconnected"
          description: "Cluster agent has been disconnected for more than 5 minutes"

      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL database has been unreachable for more than 1 minute"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 2m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis cache is down"
          description: "Redis cache has been unreachable for more than 2 minutes"

      # Performance alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="backend"}[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High API response time"
          description: "95th percentile response time is above 1 second for 5 minutes"

      - alert: HighErrorRate
        expr: rate(http_requests_total{job="backend",status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 5 minutes"

      # Resource alerts
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total{job="backend"}[5m]) * 100 > 80
        for: 10m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High CPU usage on backend"
          description: "Backend CPU usage is above 80% for 10 minutes"

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes{job="backend"} / 1024 / 1024 > 800
        for: 10m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High memory usage on backend"
          description: "Backend memory usage is above 800MB for 10 minutes"

      - alert: DatabaseConnectionPoolExhausted
        expr: pg_stat_database_numbackends{datname="hpa_db"} > 80
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "Database connection pool near limit"
          description: "Database has more than 80 active connections for 5 minutes"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / 1024 / 1024 > 400
        for: 10m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis memory usage high"
          description: "Redis is using more than 400MB of memory for 10 minutes"

      # Business logic alerts
      - alert: NoAgentsConnected
        expr: count(up{job="agent"} == 1) == 0
        for: 15m
        labels:
          severity: warning
          service: platform
        annotations:
          summary: "No cluster agents connected"
          description: "No cluster agents have been connected for 15 minutes"

      - alert: AuthenticationFailuresHigh
        expr: rate(auth_failures_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          service: auth
        annotations:
          summary: "High authentication failure rate"
          description: "More than 10 authentication failures per second for 5 minutes"

      # Disk space alerts
      - alert: DiskSpaceLow
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.1
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "Low disk space"
          description: "Less than 10% disk space remaining on root filesystem"

      # Container alerts
      - alert: ContainerRestarting
        expr: rate(container_restart_count[5m]) > 0
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "Container restarting frequently"
          description: "Container {{ $labels.container }} has been restarting"