{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hpa-chart.fullname" . }}-backend
  labels:
    {{- include "hpa-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  jwt-secret: {{ .Values.backend.secrets.JWT_SECRET | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "postgres://%s:%s@%s-postgresql:5432/%s?sslmode=disable" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.backend.secrets.DATABASE_URL | b64enc | quote }}
  {{- end }}
{{- end }}